### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ate47** [the-qa-company/qEndpoint#150]
### Part of the endpoint? (leave empty if you don't know)

- [X] Backend (hdt-qs-backend)
- [ ] Frontend (hdt-qs-frontend)
- [ ] Benchmark (hdt-qs-benchmark)
- [ ] Other

### Description of the issue

The endpoint isn't working on Windows

### Excepted behavior

Working on it

### Obtained behavior

Non closed files, missing features.

### How to reproduce

n/a

### Endpoint version

1.7.0

### Do I want to contribute to fix it?

Yes

**Comment by ate47** [comment]
Illegal `\` with Windows paths

```
org.rdfhdt.hdt.exceptions.ParserException: java.lang.IllegalArgumentException: Illegal Unicode escape sequence '\Users\wil' in: <file://C:\Users\wilat\AppData\Roaming\qendpoint\hdt-store/dump.nt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/HDT/hdt#Dataset> .
        at org.rdfhdt.hdt.rdf.parsers.RDFParserSimple.doParse(RDFParserSimple.java:121) ~[hdt-java-core-3.0.9.jar!/:na]
        at org.rdfhdt.hdt.rdf.parsers.RDFParserSimple.doParse(RDFParserSimple.java:73) ~[hdt-java-core-3.0.9.jar!/:na]
        at org.rdfhdt.hdt.header.PlainHeader.load(PlainHeader.java:137) ~[hdt-java-core-3.0.9.jar!/:na]
        at org.rdfhdt.hdt.hdt.impl.HDTImpl.mapFromHDT(HDTImpl.java:216) ~[hdt-java-core-3.0.9.jar!/:na]
        at org.rdfhdt.hdt.hdt.HDTManagerImpl.doMapIndexedHDT(HDTManagerImpl.java:102) ~[hdt-java-core-3.0.9.jar!/:na]
        at org.rdfhdt.hdt.hdt.HDTManager.mapIndexedHDT(HDTManager.java:347) ~[hdt-api-3.0.9.jar!/:na]
        at com.the_qa_company.qendpoint.store.EndpointStore.loadIndex(EndpointStore.java:398) ~[classes!/:na]
        at com.the_qa_company.qendpoint.store.EndpointStore.<init>(EndpointStore.java:174) ~[classes!/:na]
        at com.the_qa_company.qendpoint.compiler.CompiledSail.<init>(CompiledSail.java:140) ~[classes!/:na]
        at com.the_qa_company.qendpoint.compiler.CompiledSail$CompiledSailCompiler.compile(CompiledSail.java:417) ~[classes!/:na]
        at com.the_qa_company.qendpoint.controller.Sparql.initializeEndpointStore(Sparql.java:431) ~[classes!/:na]
        at com.the_qa_company.qendpoint.controller.Sparql.loadFile(Sparql.java:581) ~[classes!/:na]
        at com.the_qa_company.qendpoint.controller.EndpointController.clearData(EndpointController.java:135) ~[classes!/:na]
```
