### ISSUE TITLE
java.lang.UnsupportedClassVersionError when running the qEndpoint-wikidata docker image

### ISSUE THREAD

**Issue by FilBrb** [the-qa-company/qEndpoint#282]
### Part of the endpoint? (leave empty if you don't know)

- [ ] Backend (hdt-qs-backend)
- [ ] Core (qendpoint-core)
- [ ] Frontend (hdt-qs-frontend)
- [ ] Benchmark (hdt-qs-benchmark)
- [X] Other

### Description of the issue

Can't get the `qendpoint-wikidata` container to run. I can see from [docker hub](https://hub.docker.com/layers/qacompany/qendpoint-wikidata/1.10.0/images/sha256-268ee89d6c5ea6883ad4bd10adadf7d0194343e6c548cfc083c544a8472bcde7) that `ENV JAVA_VERSION=11.0.3`, but it needs Java version 17 to run properly.

### Obtained behavior

```
Search for wikidata_truthy index at https://qanswer-svc4.univ-st-etienne.fr/wikidata_truthy.hdt
/app/qendpoint/hdt-store/index_dev.hdt exists.
/app/qendpoint/hdt-store/index_dev.hdt.index.v1-1 exists.
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/the_qa_company/qendpoint/Application has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

### How to reproduce

`docker run -p 1234:1234 --name qendpoint-wikidata --env MEM_SIZE=6G qacompany/qendpoint-wikidata`
After downloading the index, the docker container fails to run.

### Endpoint version

1.10.0

### Do I want to contribute to fix it?

None

**Comment by ate47** [comment]
It should be fixed in the latest release. Thanks for noticing us this issue 👍
