### ISSUE TITLE
docker(latest) run error 

### ISSUE THREAD

**Issue by AryaFeng** [the-qa-company/qEndpoint#493]
### Part of the endpoint? (leave empty if you don't know)

- [X] Backend (qendpoint-backend)
- [ ] Store (qendpoint-backend)
- [X] Core (qendpoint-core)
- [ ] Frontend (qendpoint-frontend)
- [ ] Other

### Description of the issue

when i run docker run -p 1234:1234 --name qendpoint-wikidata --env MEM_SIZE=10G --env HDT_BASE=wikidata_all qacompany/qendpoint-wikidata.  
ERROR:

Search for wikidata_all index at https://qanswer-svc4.univ-st-etienne.fr/wikidata_all.hdt
starting...
Downloading the HDT index wikidata_all into /app/qendpoint/hdt-store/index_dev.hdt...
--2024-10-22 09:32:56--  https://qanswer-svc4.univ-st-etienne.fr/wikidata_all.hdt
Resolving qanswer-svc4.univ-st-etienne.fr (qanswer-svc4.univ-st-etienne.fr)... 161.3.151.12
Connecting to qanswer-svc4.univ-st-etienne.fr (qanswer-svc4.univ-st-etienne.fr)|161.3.151.12|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-10-22 09:32:56 ERROR 404: Not Found.

Downloading the HDT co-index wikidata_all into /app/qendpoint/hdt-store/index_dev.hdt.index.v1-1...
--2024-10-22 09:32:56--  https://qanswer-svc4.univ-st-etienne.fr/wikidata_all.hdt.index.v1-1
Resolving qanswer-svc4.univ-st-etienne.fr (qanswer-svc4.univ-st-etienne.fr)... 161.3.151.12
Connecting to qanswer-svc4.univ-st-etienne.fr (qanswer-svc4.univ-st-etienne.fr)|161.3.151.12|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-10-22 09:32:57 ERROR 404: Not Found.

09:32:57,827 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.4.5
09:32:57,852 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
09:32:57,857 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/app/qendpoint.jar!/BOOT-INF/classes!/logback.xml]
09:32:57,859 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@566776ad - Resource [logback.xml] occurs multiple times on the classpath.
09:32:57,859 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@566776ad - Resource [logback.xml] occurs at [jar:file:/app/qendpoint.jar!/BOOT-INF/classes!/logback.xml]
09:32:57,859 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@566776ad - Resource [logback.xml] occurs at [jar:file:/app/qendpoint.jar!/BOOT-INF/lib/qendpoint-2.1.1.jar!/logback.xml]
09:32:57,865 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@6108b2d7 - URL [jar:file:/app/qendpoint.jar!/BOOT-INF/classes!/logback.xml] is not of type file
09:32:57,971 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [STDOUT]
09:32:57,971 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:32:57,979 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09:32:57,995 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
09:32:57,995 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[ROOT]
09:32:57,996 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@66d2e7d9 - End of configuration.
09:32:57,997 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@6a2bcfcb - Registering current configuration as safe fallback point
09:32:58,356 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@41ee392b - URL [jar:file:/app/qendpoint.jar!/BOOT-INF/classes!/logback.xml] is not of type file
09:32:58,363 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [STDOUT]
09:32:58,363 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:32:58,363 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09:32:58,364 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
09:32:58,364 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[ROOT]
09:32:58,364 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@1e67a849 - End of configuration.
09:32:58,364 |-INFO in org.springframework.boot.logging.logback.SpringBootJoranConfigurator@57d5872c - Registering current configuration as safe fallback point
        ______           _             _       _
       |  ____|         | |           (_)     | |
   __ _| |__   _ __   __| |_ __   ___  _ _ __ | |_
  / _` |  __| | '_ \ / _` | '_ \ / _ \| | '_ \| __|
 | (_| | |____| | | | (_| | |_) | (_) | | | | | |_
  \__, |______|_| |_|\__,_| .__/ \___/|_|_| |_|\__|
     | |                  | |
     |_|                  |_|

09:32:58.463 [main] INFO  c.t.qendpoint.Application - Starting Application using Java 17.0.2 with PID 15 (/app/qendpoint.jar started by root in /app)
09:32:58.465 [main] INFO  c.t.qendpoint.Application - No active profile set, falling back to 1 default profile: "default"
09:32:59.657 [main] INFO  c.t.qendpoint.controller.Sparql - using applicationDirectory: ./qendpoint
09:32:59.658 [main] INFO  c.t.qendpoint.controller.Sparql - locationHdt:                /app/./qendpoint/hdt-store/
09:32:59.658 [main] INFO  c.t.qendpoint.controller.Sparql - locationNative:             /app/./qendpoint/native-store/
09:32:59.852 [main] INFO  c.t.qendpoint.store.EndpointStore - CHECK IF A PREVIOUS MERGE WAS STOPPED
09:32:59.916 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server
09:32:59.931 [main] INFO  o.s.b.a.l.ConditionEvaluationReportLogger - 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
09:32:59.948 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.context.ApplicationContextException: Unable to start web server
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:164)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:578)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:150)
	at com.the_qa_company.qendpoint.Application.main(Application.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Error creating bean with name 'webConfig': Unsatisfied dependency expressed through field 'sparql': Error creating bean with name 'sparql': Invocation of init method failed
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:606)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:218)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:181)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:161)
	... 15 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webConfig': Unsatisfied dependency expressed through field 'sparql': Error creating bean with name 'sparql': Invocation of init method failed
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:712)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:692)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:133)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:481)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1397)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:662)
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.getWebServerFactoryCustomizerBeans(WebServerFactoryCustomizerBeanPostProcessor.java:87)
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.getCustomizers(WebServerFactoryCustomizerBeanPostProcessor.java:78)
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:70)
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:58)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:420)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1743)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
	... 23 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sparql': Invocation of init method failed
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:420)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1743)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1405)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1325)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:709)
	... 41 common frames omitted
Caused by: java.io.EOFException: null
	at com.the_qa_company.qendpoint.core.util.io.IOUtil.readChars(IOUtil.java:427)
	at com.the_qa_company.qendpoint.core.options.ControlInformation.load(ControlInformation.java:96)
	at com.the_qa_company.qendpoint.core.hdt.impl.HDTImpl.mapFromHDT(HDTImpl.java:205)
	at com.the_qa_company.qendpoint.core.hdt.HDTManagerImpl.doMapIndexedHDT(HDTManagerImpl.java:106)
	at com.the_qa_company.qendpoint.core.hdt.HDTManager.mapIndexedHDT(HDTManager.java:454)
	at com.the_qa_company.qendpoint.store.EndpointStore.loadIndex(EndpointStore.java:552)
	at com.the_qa_company.qendpoint.store.EndpointStore.<init>(EndpointStore.java:221)
	at com.the_qa_company.qendpoint.compiler.CompiledSail.<init>(CompiledSail.java:158)
	at com.the_qa_company.qendpoint.compiler.CompiledSail$CompiledSailCompiler.compile(CompiledSail.java:596)
	at com.the_qa_company.qendpoint.controller.Sparql.initializeEndpointStore(Sparql.java:326)
	at com.the_qa_company.qendpoint.controller.Sparql.init(Sparql.java:191)
	at com.the_qa_company.qendpoint.controller.Sparql.runClient(Sparql.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:424)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:368)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:192)
	... 53 common frames omitted

### Do I want to contribute to fix it?

None

**Comment by ate47** [comment]
I renamed it, can you retry?

**Comment by AryaFeng** [comment]
> I renamed it, can you retry?

Do you mean I should re-download the docker image and run it?

**Comment by ate47** [comment]
No, I renamed it on the server. I think only running it again would be enough

**Comment by AryaFeng** [comment]
> No, I renamed it on the server. I think only running it again would be enough

thank you! It is ok! Thank you for your quick reply

**Comment by ate47** [comment]
First it will depend on how fast you can download the 321GB, then on how fast your computer can map the index. On mine it takes ~4min, on some >10min

**Comment by ate47** [comment]
Did you have another question or can I close the issue @AryaFeng?

**Comment by AryaFeng** [comment]
thank your help. u can close this issue



---Original---
From: "Antoine ***@***.***&gt;
Date: Thu, Oct 24, 2024 17:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [the-qa-company/qEndpoint] docker(latest) run error  (Issue #493)




 
Did you have another question or can I close the issue @AryaFeng?
